### ISSUE TITLE
help add discord web hook notify

### ISSUE THREAD

**Issue by dancebunny98** [dichternebel/scs-telemetry-json-service#1]
pls add examples for add discord web hook

**Comment by dichternebel** [comment]
Do you you want to post messages to discord using the output of this json service? If so, this is totally up to you then. I would suggest to create a small application like the [discord-rss-webhook](https://github.com/dichternebel/discord-rss-webhook) that periodically gets data from the json service and sends certain events to discord.

**Comment by dancebunny98** [comment]
It would be great if you, as an author, could help me with the integration of this.

**Comment by dichternebel** [comment]
Sorry. But no. This is not in scope of this json service. It's meant to be consumed e.g. by other programs. That said you have to create something on your own that reads data from the provided service endpoint and sends it to Discord.

To get the data you might use the Fetch API:
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

And to send that data using webhooks you might have a look here to get started:
https://birdie0.github.io/discord-webhooks-guide/index.html

You might also start from scratch using RenCloud's scs-sdk-plugin directly:
https://github.com/RenCloud/scs-sdk-plugin
