### ISSUE TITLE
Make listening address configurable

### ISSUE THREAD

**Issue by BaldFabi** [dichternebel/scs-telemetry-json-service#2]
Any chance to make the listening address configurable instead of hardcoded localhost?

**Comment by dichternebel** [comment]
@BaldFabi Had to fix another bug in the shared template file and created a new release. Please download and test it.

**Comment by BaldFabi** [comment]
It works the same. But I found out that still only localhost as address works. If you put anything else than localhost into the address option no port will open on any address not even localhost.

**Comment by dichternebel** [comment]
That's correct. You have to add an `urlacl` when using something else but `localhost`.
If your IP is 192.168.0.42 then you would need to run this command assuming your OS is german:
`netsh http add urlacl url=http://192.168.0.42:6969/ user=Jeder`
Setting that urlacl has the side-effect that a call to localhost will no longer work... I will check if I can set this from the program itself to the given address.

**Comment by dichternebel** [comment]
I will switch from HttpListener to TcpListener to make this feature possible without the need of setting the address whatsoever.

**Comment by dichternebel** [comment]
Solved with https://github.com/dichternebel/scs-telemetry-json-service/releases/tag/v0.9.5

**Comment by BaldFabi** [comment]
Will test it, thank you
